/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Not_authorizedRouteImport } from './routes/not_authorized'
import { Route as AdminIposRouteImport } from './routes/_admin/ipos'
import { Route as AdminLeaderboardRouteImport } from './routes/_admin/leaderboard'
import { Route as AdminMarketRouteImport } from './routes/_admin/market'
import { Route as AdminNewsRouteImport } from './routes/_admin/news'
import { Route as AdminStocksRouteImport } from './routes/_admin/stocks'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AuthResetpasswordRouteImport } from './routes/auth/resetpassword'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AdminStockIdRouteImport } from './routes/_admin/stock.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Not_authorizedRoute = Not_authorizedRouteImport.update({
  id: '/not_authorized',
  path: '/not_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIposRoute = AdminIposRouteImport.update({
  id: '/ipos',
  path: '/ipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketRoute = AdminMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthResetpasswordRoute = AuthResetpasswordRouteImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockIdRoute = AdminStockIdRouteImport.update({
  id: '/stock/$id',
  path: '/stock/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/ipos': typeof AdminIposRoute
  '/leaderboard': typeof AdminLeaderboardRoute
  '/market': typeof AdminMarketRoute
  '/news': typeof AdminNewsRoute
  '/stocks': typeof AdminStocksRoute
  '/users': typeof AdminUsersRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/stock/$id': typeof AdminStockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/ipos': typeof AdminIposRoute
  '/leaderboard': typeof AdminLeaderboardRoute
  '/market': typeof AdminMarketRoute
  '/news': typeof AdminNewsRoute
  '/stocks': typeof AdminStocksRoute
  '/users': typeof AdminUsersRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/stock/$id': typeof AdminStockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/_admin/ipos': typeof AdminIposRoute
  '/_admin/leaderboard': typeof AdminLeaderboardRoute
  '/_admin/market': typeof AdminMarketRoute
  '/_admin/news': typeof AdminNewsRoute
  '/_admin/stocks': typeof AdminStocksRoute
  '/_admin/users': typeof AdminUsersRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_admin/stock/$id': typeof AdminStockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/not_authorized'
    | '/ipos'
    | '/leaderboard'
    | '/market'
    | '/news'
    | '/stocks'
    | '/users'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/stock/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/not_authorized'
    | '/ipos'
    | '/leaderboard'
    | '/market'
    | '/news'
    | '/stocks'
    | '/users'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/stock/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/not_authorized'
    | '/_admin/ipos'
    | '/_admin/leaderboard'
    | '/_admin/market'
    | '/_admin/news'
    | '/_admin/stocks'
    | '/_admin/users'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/_admin/stock/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  Not_authorizedRoute: typeof Not_authorizedRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not_authorized': {
      id: '/not_authorized'
      path: '/not_authorized'
      fullPath: '/not_authorized'
      preLoaderRoute: typeof Not_authorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/ipos': {
      id: '/_admin/ipos'
      path: '/ipos'
      fullPath: '/ipos'
      preLoaderRoute: typeof AdminIposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/leaderboard': {
      id: '/_admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/market': {
      id: '/_admin/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AdminMarketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/news': {
      id: '/_admin/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/stocks': {
      id: '/_admin/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/stock/$id': {
      id: '/_admin/stock/$id'
      path: '/stock/$id'
      fullPath: '/stock/$id'
      preLoaderRoute: typeof AdminStockIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIposRoute: typeof AdminIposRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminMarketRoute: typeof AdminMarketRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminStockIdRoute: typeof AdminStockIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIposRoute: AdminIposRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminMarketRoute: AdminMarketRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminStockIdRoute: AdminStockIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  Not_authorizedRoute: Not_authorizedRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
