/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Not_authorizedRouteImport } from './routes/not_authorized'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AdminStocksRouteImport } from './routes/_admin/stocks'
import { Route as AdminMarketRouteImport } from './routes/_admin/market'
import { Route as AdminStockIdRouteImport } from './routes/_admin/stock.$id'

const Not_authorizedRoute = Not_authorizedRouteImport.update({
  id: '/not_authorized',
  path: '/not_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketRoute = AdminMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockIdRoute = AdminStockIdRouteImport.update({
  id: '/stock/$id',
  path: '/stock/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/market': typeof AdminMarketRoute
  '/stocks': typeof AdminStocksRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/stock/$id': typeof AdminStockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/market': typeof AdminMarketRoute
  '/stocks': typeof AdminStocksRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/stock/$id': typeof AdminStockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/not_authorized': typeof Not_authorizedRoute
  '/_admin/market': typeof AdminMarketRoute
  '/_admin/stocks': typeof AdminStocksRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_admin/stock/$id': typeof AdminStockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/not_authorized'
    | '/market'
    | '/stocks'
    | '/auth/signin'
    | '/auth/signup'
    | '/stock/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/not_authorized'
    | '/market'
    | '/stocks'
    | '/auth/signin'
    | '/auth/signup'
    | '/stock/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/not_authorized'
    | '/_admin/market'
    | '/_admin/stocks'
    | '/auth/signin'
    | '/auth/signup'
    | '/_admin/stock/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  Not_authorizedRoute: typeof Not_authorizedRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not_authorized': {
      id: '/not_authorized'
      path: '/not_authorized'
      fullPath: '/not_authorized'
      preLoaderRoute: typeof Not_authorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/stocks': {
      id: '/_admin/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/market': {
      id: '/_admin/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AdminMarketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/stock/$id': {
      id: '/_admin/stock/$id'
      path: '/stock/$id'
      fullPath: '/stock/$id'
      preLoaderRoute: typeof AdminStockIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMarketRoute: typeof AdminMarketRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminStockIdRoute: typeof AdminStockIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMarketRoute: AdminMarketRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminStockIdRoute: AdminStockIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  Not_authorizedRoute: Not_authorizedRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
